<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'DB_USER' => '',
  'DB_PASS' => 'p@ss#word',
  'DB_NAME' => 'my__database',
  'START_TIME' => 'Thu Aug 6 13:58:15 AEST 2026',
  'APP_SECRET' => 'a1b2c3d4e5f6a1b2c3d4e5f6',
  'DATABASE_URL' => 'sqlite:///%kernel.project_dir%/var/data.db',
);
